---
Name: form_submission_config
---
SilverStripe\UserForms\Model\UserDefinedForm:
  extensions:
    - Symbiote\UdfObjects\UserFormExtension

SilverStripe\UserForms\Model\Submission\SubmittedForm:
  extensions:
    - Symbiote\UdfObjects\MappedSubmittedFormExtension

