---
Name: form_submission_config
---
SilverStripe\UserForms\Model\UserDefinedForm:
  extensions:
    - Symbiote\UdfObjects\UserFormExtension
DNADesign\ElementalUserForms\Model\ElementForm:
  extensions:
    - Symbiote\UdfObjects\UserFormExtension

SilverStripe\UserForms\Model\Submission\SubmittedForm:
  extensions:
    - Symbiote\UdfObjects\MappedSubmittedFormExtension


---
Name: form_submission_workflow_config
Only:
  moduleexists:
    - symbiote/silverstripe-advancedworkflow
---
Symbiote\UdfObjects\FormSubmissionList:
  extensions:
    - Symbiote\AdvancedWorkflow\Extensions\WorkflowApplicable
Symbiote\UdfObjects\FormSubmissionListAdmin:
  extensions:
    - Symbiote\AdvancedWorkflow\Extensions\AdvancedWorkflowExtension

---
Name: form_submission_elemental
Only:
  moduleexists:
    - dnadesign/silverstripe-elemental-userforms
---
Symbiote\UdfObjects\FormResponseExtension:
  has_one:
    FromElement: DNADesign\ElementalUserForms\Model\ElementForm
